CREATE DATABASE QUANLYCANTIN
GO

USE QUANLYCANTIN
GO

CREATE TABLE KHACHHANG (
    IDKH INT IDENTITY PRIMARY KEY,
	TENKH NVARCHAR(50),
	GIOITINH NVARCHAR(20),
	NGAYSINH DATE,
	DIACHI NVARCHAR(100),
	SDT NVARCHAR(20),
	EMAIL NVARCHAR(100),
	TAIKHOAN NVARCHAR(50),
	MATKHAU NVARCHAR(50),
)

CREATE TABLE CHUCVU (
	IDCV INT IDENTITY PRIMARY KEY,
	TENCV NVARCHAR(50),
)

CREATE TABLE TAIKHOAN (
	IDTK INT IDENTITY PRIMARY KEY,
	TENDANGNHAP NVARCHAR(50),
	MATKHAU NVARCHAR(50),
	IDCV INT FOREIGN KEY REFERENCES CHUCVU(IDCV),
)

CREATE TABLE NHANVIEN (
	IDNV INT IDENTITY PRIMARY KEY,
	TENNV NVARCHAR(50),
	GIOITINH NVARCHAR(20),
	NGAYSINH DATE,
	DIACHI NVARCHAR(100),
	SDT NVARCHAR(20),
	EMAIL NVARCHAR(50),
	IDCV INT FOREIGN KEY REFERENCES CHUCVU(IDCV),
	LUONGCA INT,
	HINHANHNV NVARCHAR(100),
)

CREATE TABLE CHAMCONG (
	IDNV INT FOREIGN KEY REFERENCES NHANVIEN(IDNV),
	NGAYLAM DATE,
	CATRUC NVARCHAR(20),
	PRIMARY KEY(IDNV, NGAYLAM, CATRUC),
)

CREATE TABLE TRALUONG (
	IDNV INT FOREIGN KEY REFERENCES NHANVIEN(IDNV) ,
	NGAYBATDAU DATE,
	NGAYKETTHUC DATE,
	SOCALAM INT,
	LUONGTHUONG INT,
	LUONGTONG INT,
	PRIMARY KEY(IDNV,NGAYBATDAU,NGAYKETTHUC),
)

CREATE TABLE SANPHAM (
	IDSP INT IDENTITY PRIMARY KEY,
	TENSP NVARCHAR(50),
	GIA INT,
	SLCONLAI INT,
	DONVITINH NVARCHAR(50),
	LOAI NVARCHAR(20),
	HINHANHSP NVARCHAR(100),
)

CREATE TABLE NHACUNGCAP(
   IDNCC INT IDENTITY PRIMARY KEY,
   TENNCC NVARCHAR(50),
   DIACHI NVARCHAR(100),
   SDT NVARCHAR(20),
   EMAIL NVARCHAR(50),
)

CREATE TABLE NHAPHANG (
	IDSP INT FOREIGN KEY REFERENCES SANPHAM(IDSP),
	SOLUONG INT,
	NGAYNHAP DATE,
	IDNCC INT FOREIGN KEY (IDNCC) REFERENCES NHACUNGCAP(IDNCC)
	PRIMARY KEY (IDSP, NGAYNHAP),
)

CREATE TABLE HOADON (
	IDHD INT IDENTITY PRIMARY KEY,
	NGAYLAP DATE,
	TONGTIEN INT,
	GIAOHANG BIT,
	TENKH NVARCHAR(50),
	SDT NVARCHAR(20),
	DIACHI NVARCHAR(50),
	GHICHU NVARCHAR(100),
	TRANGTHAI NVARCHAR(30),
	IDKH INT FOREIGN KEY (IDKH) REFERENCES KHACHHANG(IDKH),
)

CREATE TABLE CHITIETHOADON (
	IDHD INT FOREIGN KEY REFERENCES HOADON(IDHD),
	IDSP INT FOREIGN KEY REFERENCES SANPHAM(IDSP),
	SOLUONG INT,
	THANHTIEN INT,
	PRIMARY KEY (IDHD, IDSP),
)

CREATE PROC sp_getDataReportNhapHang @tuNgay DATETIME, @denNgay DATETIME
AS
	SELECT IDSP, SOLUONG, NGAYNHAP, TENNCC
	FROM NHAPHANG NH INNER JOIN NHACUNGCAP NCC ON NH.IDNCC = NCC.IDNCC
	WHERE NGAYNHAP >= @tuNgay AND NGAYNHAP <= @denNgay

CREATE PROC sp_getDataReportDoanhThu @tuNgay DATETIME, @denNgay DATETIME
AS
	SELECT IDHD, NGAYLAP, TENKH, DIACHI, SDT, TONGTIEN
	FROM HOADON
	WHERE NGAYLAP >= @tuNgay AND NGAYLAP <= @denNgay

CREATE PROC sp_getDataReportHoaDon @idHD INT
AS
	SELECT *
	FROM HOADON
	WHERE IDHD = @idHD

CREATE PROC sp_getDataReportCTHD @idHD INT
AS
	SELECT *
	FROM CHITIETHOADON CTHD INNER JOIN SANPHAM SP ON CTHD.IDSP = SP.IDSP
	WHERE IDHD = @idHD

/* INSERT KHACHHANG */

INSERT INTO KHACHHANG VALUES (N'Hoàng Đình Thiên Đông', ' Nam', '1999-02-05', 'thiendongntt', 'kuti2710', N'Quận 9, HCM', 'thiendonggtvt@gmail.com', '0298294385')
INSERT INTO KHACHHANG VALUES (N'Trần Minh Hảo', 'Nam', '2020-01-01', 'minhhao123', 'minhhao123', N'TP HCM', 'minhhao.hh@gmail.com', '012345678 ')

/* INSERT CHUCVU */
INSERT INTO CHUCVU VALUES(N'Quản lý')
INSERT INTO CHUCVU VALUES(N'Nhân viên giao hàng')
INSERT INTO CHUCVU VALUES(N'Nhân viên bán hàng')
INSERT INTO CHUCVU VALUES(N'Quản trị viên')

/* INSERT TAIKHOAN */

INSERT INTO TAIKHOAN VALUES(N'quanly', N'quanly', 1)
INSERT INTO TAIKHOAN VALUES(N'banhang', N'banhang', 3)
INSERT INTO TAIKHOAN VALUES(N'giaohang', N'giaohang', 2)
INSERT INTO TAIKHOAN VALUES(N'admin', N'admin', 4)


/* INSERT NHANVIEN */

INSERT INTO NHANVIEN (TENNV, GIOITINH, NGAYSINH, DIACHI, SDT, EMAIL, IDCV, LUONGCA, HINHANHNV) VALUES (N'Trần Minh Hảo', N'Nam', '2000-12-04', N'Bình Định', '0839518880', 'minhhao.hh@gmail.com', 1, 150000, 'D:\QuanLyCanTin\Images\Images\NhanVien\Hao.jpg')
INSERT INTO NHANVIEN (TENNV, GIOITINH, NGAYSINH, DIACHI, SDT, EMAIL, IDCV, LUONGCA, HINHANHNV) VALUES (N'Hoàng Đình Thiên Đông', N'Nam', '1999-02-03', N'Dak Nông', '0398294385', 'thiendong@gmail.com', 1, 150000, 'D:\QuanLyCanTin\Images\Images\NhanVien\Dong.jpg')
INSERT INTO NHANVIEN (TENNV, GIOITINH, NGAYSINH, DIACHI, SDT, EMAIL, IDCV, LUONGCA, HINHANHNV) VALUES (N'Trần Tiến Đạt', N'Nam', '2000-01-01', N'TP.HCM', '012345678', 'dat@gmail.com', 2, 100000, 'D:\QuanLyCanTin\Images\Images\NhanVien\Dat.jpg')
INSERT INTO NHANVIEN (TENNV, GIOITINH, NGAYSINH, DIACHI, SDT, EMAIL, IDCV, LUONGCA, HINHANHNV) VALUES (N'Nguyễn Duy Thắng', N'Nam', '2000-01-01', N'Phú Yên', '012345678', 'thang@gmail.com', 2, 100000, 'D:\QuanLyCanTin\Images\Images\NhanVien\Thang.jpg')
INSERT INTO NHANVIEN (TENNV, GIOITINH, NGAYSINH, DIACHI, SDT, EMAIL, IDCV, LUONGCA, HINHANHNV) VALUES (N'Đặng Bình Phước', N'Nam', '2000-01-01', N'Bình Phước', '012345678', 'phuoc@gmail.com', 3, 100000, 'D:\QuanLyCanTin\Images\Images\NhanVien\Phuoc.jpg')
INSERT INTO NHANVIEN (TENNV, GIOITINH, NGAYSINH, DIACHI, SDT, EMAIL, IDCV, LUONGCA, HINHANHNV) VALUES (N'Lê Minh Thái', N'Nam', '2000-01-01', N'Dak Lak', '012345678', 'thai@gmail.com', 2, 100000, 'D:\QuanLyCanTin\Images\Images\NhanVien\Thai.jpg')
INSERT INTO NHANVIEN (TENNV, GIOITINH, NGAYSINH, DIACHI, SDT, EMAIL, IDCV, LUONGCA, HINHANHNV) VALUES (N'Hồ Nguyễn Thanh Phong', N'Nam', '2000-01-01', N'TP.HCM', '012345678', 'phong@gmail.com', 2, 100000, 'D:\QuanLyCanTin\Images\Images\NhanVien\Phong.jpg')
INSERT INTO NHANVIEN (TENNV, GIOITINH, NGAYSINH, DIACHI, SDT, EMAIL, IDCV, LUONGCA, HINHANHNV) VALUES (N'Đặng Văn Thọ', N'Nam', '2000-01-01', N'Dak Lak', '012345678', 'tho@gmail.com', 3, 100000, 'D:\QuanLyCanTin\Images\Images\NhanVien\Tho.jpg')
INSERT INTO NHANVIEN (TENNV, GIOITINH, NGAYSINH, DIACHI, SDT, EMAIL, IDCV, LUONGCA, HINHANHNV) VALUES (N'Lê Trần Xuân Sơn', N'Nam', '2000-01-01', N'TP.HCM', '012345678', 'son@gmail.com', 2, 100000, 'D:\QuanLyCanTin\Images\Images\NhanVien\Son.jpg')
INSERT INTO NHANVIEN (TENNV, GIOITINH, NGAYSINH, DIACHI, SDT, EMAIL, IDCV, LUONGCA, HINHANHNV) VALUES (N'Đỗ Hoàng Gia', N'Nam', '2000-01-01', N'Vũng Tàu', '012345678', 'gia@gmail.com', 2, 100000, 'D:\QuanLyCanTin\Images\Images\NhanVien\Gia.jpg')
INSERT INTO NHANVIEN (TENNV, GIOITINH, NGAYSINH, DIACHI, SDT, EMAIL, IDCV, LUONGCA, HINHANHNV) VALUES (N'Võ Phi Quân', N'Nam', '2000-01-01', N'TP.HCM', '012345678', 'quan@gmail.com', 3, 100000, 'D:\QuanLyCanTin\Images\Images\NhanVien\Quan.jpg')


/* INSERT CHAMCONG */

INSERT INTO CHAMCONG (IDNV, NGAYLAM, CATRUC) VALUES (1, '1-1-2020', N'Sáng')
INSERT INTO CHAMCONG (IDNV, NGAYLAM, CATRUC) VALUES (2, '2-2-2021', N'Chiều')
INSERT INTO CHAMCONG (IDNV, NGAYLAM, CATRUC) VALUES (3, '2-3-2021', N'Sáng')
INSERT INTO CHAMCONG (IDNV, NGAYLAM, CATRUC) VALUES (4, '5-5-2021', N'Chiều')
INSERT INTO CHAMCONG (IDNV, NGAYLAM, CATRUC) VALUES (5, '6-6-2020', N'Sáng')
INSERT INTO CHAMCONG (IDNV, NGAYLAM, CATRUC) VALUES (6, '1-2-2021', N'Chiều')


/* INSERT TRALUONG */


/* INSERT BẢNG SẢN PHẨM*/

INSERT INTO SANPHAM VALUES(N'Cocacola', 10000, 100, N'Lon', N'Đồ uống', 'D:\QuanLyCanTin\Images\Images\DoUong\coca.jpg')
INSERT INTO SANPHAM VALUES(N'Pepsi', 10000, 100, N'Lon', N'Đồ uống', 'D:\QuanLyCanTin\Images\Images\DoUong\pepsi.jpg')
INSERT INTO SANPHAM VALUES(N'7UP', 10000, 100, N'Lon', N'Đồ uống', 'D:\QuanLyCanTin\Images\Images\DoUong\7up.jpg')
INSERT INTO SANPHAM VALUES(N'Number One', 10000, 100, N'Chai', N'Đồ uống', 'D:\QuanLyCanTin\Images\Images\DoUong\number1.jpg')
INSERT INTO SANPHAM VALUES(N'Bò húc', 15000, 100, N'Lon', N'Đồ uống', 'D:\QuanLyCanTin\Images\Images\DoUong\redbull.jpg')
INSERT INTO SANPHAM VALUES(N'Nước suối', 6000, 100, N'Chai', N'Đồ uống', 'D:\QuanLyCanTin\Images\Images\DoUong\nuocsuoi.jpg')
INSERT INTO SANPHAM VALUES(N'Cafe đen đá', 12000, 100, N'Ly', N'Đồ uống', 'D:\QuanLyCanTin\Images\Images\DoUong\cafedenda.jpg')
INSERT INTO SANPHAM VALUES(N'Cafe sữa đá', 15000, 100, N'Ly', N'Đồ uống', 'D:\QuanLyCanTin\Images\Images\DoUong\cafesuada.jpg')
INSERT INTO SANPHAM VALUES(N'Trà sữa', 20000, 100, N'Ly', N'Đồ uống', 'D:\QuanLyCanTin\Images\Images\DoUong\trasua.jpg')

INSERT INTO SANPHAM VALUES(N'Bánh tráng trộn', 15000, 100, N'Phần', N'Đồ ăn vật', 'D:\QuanLyCanTin\Images\Images\DoAnVat\banhtrangtron.jpg')
INSERT INTO SANPHAM VALUES(N'Cơm cháy', 10000, 100, N'Phần', N'Đồ ăn vật', 'D:\QuanLyCanTin\Images\Images\DoAnVat\comchay.jpg')
INSERT INTO SANPHAM VALUES(N'Khoai tây chiên', 15000, 100, N'Phần', N'Đồ ăn vật', 'D:\QuanLyCanTin\Images\Images\DoAnVat\khoaitaychien.jpg')
INSERT INTO SANPHAM VALUES(N'Bim bim', 10000, 100, N'Phần', N'Đồ ăn vật', 'D:\QuanLyCanTin\Images\Images\DoAnVat\snack.jpg')

INSERT INTO SANPHAM VALUES(N'Bánh mì', 10000, 100, N'Phần', N'Đồ ăn sáng', 'D:\QuanLyCanTin\Images\Images\DoAnSang\banhmi.jpg')
INSERT INTO SANPHAM VALUES(N'Bánh ướt', 15000, 100, N'Phần', N'Đồ ăn sáng', 'D:\QuanLyCanTin\Images\Images\DoAnSang\banhuot.jpg')
INSERT INTO SANPHAM VALUES(N'Bún bò', 25000, 100, N'Tô', N'Đồ ăn sáng', 'D:\QuanLyCanTin\Images\Images\DoAnSang\bunbo.jpg')
INSERT INTO SANPHAM VALUES(N'Mì tôm trứng', 15000, 100, N'Tô', N'Đồ ăn sáng', 'D:\QuanLyCanTin\Images\Images\DoAnSang\mitomtrung.jpg')
INSERT INTO SANPHAM VALUES(N'Phở', 25000, 100, N'Tô', N'Đồ ăn sáng', 'D:\QuanLyCanTin\Images\Images\DoAnSang\pho.jpg')
INSERT INTO SANPHAM VALUES(N'Xôi mặn', 15000, 100, N'Phần', N'Đồ ăn sáng', 'D:\QuanLyCanTin\Images\Images\DoAnSang\xoiman.jpg')
INSERT INTO SANPHAM VALUES(N'Xôi ngọt', 15000, 100, N'Phần', N'Đồ ăn sáng', 'D:\QuanLyCanTin\Images\Images\DoAnSang\xoingot.jpg')

INSERT INTO SANPHAM VALUES(N'Xoài', 10000, 100, N'Trái', N'Khác', 'D:\QuanLyCanTin\Images\Images\Khac\xoai.jpg')
INSERT INTO SANPHAM VALUES(N'Ổi', 10000, 100, N'Trái', N'Khác', 'D:\QuanLyCanTin\Images\Images\Khac\oi.jpg')

/* INSERT NHACUNGCAP */

INSERT INTO NHACUNGCAP VALUES(N'Nguyễn Duy Thắng', 'duythang@gmail.com', N'Quận 9, HCM', '0976576123')
INSERT INTO NHACUNGCAP VALUES(N'Dặng Văn Thọ', 'vantho@gmail.com', N'Quận 10, HCM', '0939567345')
INSERT INTO NHACUNGCAP VALUES(N'Nguyễn Tri Tân', 'tritan@gmail.com', N'Quận Thủ Đức HCM', '0360364120')

/* INSERT NHAPHANG */

INSERT INTO NHAPHANG VALUES(1, 99, '2020-01-01', 1)
INSERT INTO NHAPHANG VALUES(1, 60, '2021-01-20', 1)
INSERT INTO NHAPHANG VALUES(2, 70, '2021-02-10', 2)
INSERT INTO NHAPHANG VALUES(2, 80, '2020-03-29', 2)
INSERT INTO NHAPHANG VALUES(2, 100, '2021-03-12', 2)
INSERT INTO NHAPHANG VALUES(3, 110, '2020-04-28', 1)
INSERT INTO NHAPHANG VALUES(4, 50, '2021-05-09', 3)
INSERT INTO NHAPHANG VALUES(5, 20, '2020-06-03', 1)
INSERT INTO NHAPHANG VALUES(5, 45, '2021-06-04', 3)

/* INSERT HOADON */
SELECT * FROM SANPHAM
SELECT * FROM KHACHHANG

INSERT INTO HOADON VALUES('05-05-2021', 30000, 1, N'Hoàng Đình Thiên Đông', '0398294385', N'Quận 9, HCM', NULL, N'Đang giao', 1)
INSERT INTO HOADON VALUES('05-06-2021', 40000, 1, N'Hoàng Đình Thiên Đông', '0398294385', N'Quận 9, HCM', NULL, N'Đang giao', 1)
INSERT INTO HOADON VALUES('05-08-2021', 20000, 1, N'Hoàng Đình Thiên Đông', '0398294385', N'Quận 9, HCM', NULL, N'Đang giao', 1)
INSERT INTO HOADON VALUES('03-07-2021', 10000, 1, N'Trần Minh Hảo', '012345678', N'TP HCM', NULL, N'Đang giao', 2)
INSERT INTO HOADON VALUES('10-01-2021', 20000, 1, N'Trần Minh Hảo', '012345678', N'TP HCM', NULL, N'Đang giao', 2)
INSERT INTO HOADON VALUES('06-07-2021', 100000, 1, N'Trần Minh Hảo', '012345678', N'TP HCM', NULL, N'Đang giao', 2)
INSERT INTO HOADON VALUES('06-06-2021', 200000, 1, N'Hoàng Đình Thiên Đông', '0398294385', N'Quận 9, HCM', NULL, N'Đang giao', 1)



/* INSERT CHITIETHOADON */
INSERT INTO CHITIETHOADON VALUES(1, 1, 2, 20000)
INSERT INTO CHITIETHOADON VALUES(1, 6, 1, 10000)

INSERT INTO CHITIETHOADON VALUES(2, 7, 2, 12000)
INSERT INTO CHITIETHOADON VALUES(2, 14, 2, 8000)
INSERT INTO CHITIETHOADON VALUES(2, 11, 1, 20000)

INSERT INTO CHITIETHOADON VALUES(3, 1, 1, 10000)
INSERT INTO CHITIETHOADON VALUES(3, 6, 1, 10000)

INSERT INTO CHITIETHOADON VALUES(4, 1, 1, 10000)

INSERT INTO CHITIETHOADON VALUES(5, 1, 1, 10000)
INSERT INTO CHITIETHOADON VALUES(5, 13, 1, 10000)

INSERT INTO CHITIETHOADON VALUES(6, 10, 4, 50000)
INSERT INTO CHITIETHOADON VALUES(6, 1, 3, 30000)
INSERT INTO CHITIETHOADON VALUES(6, 11, 1, 20000)

INSERT INTO CHITIETHOADON VALUES(7, 6, 10, 100000)
INSERT INTO CHITIETHOADON VALUES(7, 4, 10, 50000)
INSERT INTO CHITIETHOADON VALUES(7,2, 10, 30000)
INSERT INTO CHITIETHOADON VALUES(7, 11, 1, 20000)








